# Custom Language File for Launcher Customizer

[ejs.app]
title = "AzaCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://azacraft.de"
mediaTwitterURL = "https://x.com/Zelthoriaismp87"
mediaInstagramURL = "https://www.tiktok.com/@_zsmp_"
mediaYouTubeURL = "https://youtube.com/@zsmpofc?si=bEThHknf_WXB7wqp"
mediaDiscordURL = "https://discord.gg/azacraft"

[ejs.settings]
sourceGithubLink = "https://github.com/AzazeliTV/AzaCraftLauncher"
supportLink = "https://github.com/AzazeliTV/AzaCraftLauncher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO HASTA STUDIOS"
welcomeDescription = """
AzaCraft is a custom Minecraft launcher focused on performance and community. From crafting immersive mods to managing extraordinary Minecraft servers, our mission is clear: to deliver the ultimate gaming experience for players around the globe.

This launcher connects you directly to the AzaCraft servers and modpacks for a smooth and simple experience.
"""

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"